# name: Cypress Tests

# on: push

# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v5
#         with:
#           build: npm run build
#           start: npm start
# .github/workflows/cypress.yml
# 這是一個 YAML 註釋，它以 # 開始，直到該行的結束都是註釋。

name: Cypress
# 工作流程的名稱，這裡取名為 Cypress。

on:
  push:
    branches: [main]
# 定義觸發工作流程的事件，這裡指的是在 main 分支上 push 事件觸發工作流程。

jobs:
  cypress:
    runs-on: ubuntu-latest
# 定義工作流程中的工作（job），這裡只有一個名為 cypress 的工作。這個工作運行在最新版的 Ubuntu 環境上。

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
# 定義工作中的步驟（step），這裡定義了一個名為 Checkout code 的步驟，使用了 actions/checkout@v2 的 action 來檢出原始碼。

      - name: Install dependencies
        run: npm install
# 定義了一個名為 Install dependencies 的步驟，運行 npm install 命令來安裝相關的依賴項。

      - name: Start server
        run: npm start &
        background: true
# 定義了一個名為 Start server 的步驟，運行 npm start 命令來啟動應用程式的本地伺服器，& 符號表示在後台運行該命令，background: true 表示在後台運行該步驟。

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          record: true
# 定義了一個名為 Run Cypress 的步驟，使用 Cypress 的 GitHub Action，運行 Cypress 測試。這裡使用了 cypress-io/github-action@v2 的 action，with 子項定義了一個 record 選項，將測試結果記錄到 Cypress Dashboard 中。
